/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const GenerationParameters = IDL.Record({
  'roughness' : IDL.Float64,
  'patternStyle' : IDL.Text,
  'metalness' : IDL.Float64,
  'colorPalette' : IDL.Vec(IDL.Text),
  'tilingScale' : IDL.Float64,
});
export const MaterialType = IDL.Variant({
  'metal' : IDL.Null,
  'organic' : IDL.Null,
  'wood' : IDL.Null,
  'stone' : IDL.Null,
  'plastic' : IDL.Null,
  'fabric' : IDL.Null,
});
export const TexturePreset = IDL.Record({
  'owner' : IDL.Principal,
  'name' : IDL.Text,
  'parameters' : GenerationParameters,
  'timestamp' : IDL.Int,
  'materialType' : MaterialType,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deletePreset' : IDL.Func([IDL.Text], [], []),
  'getAllPresets' : IDL.Func([], [IDL.Vec(TexturePreset)], ['query']),
  'getAllPresetsByName' : IDL.Func([], [IDL.Vec(TexturePreset)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPreset' : IDL.Func([IDL.Text], [IDL.Opt(TexturePreset)], ['query']),
  'getPresetsByMaterialType' : IDL.Func(
      [MaterialType],
      [IDL.Vec(TexturePreset)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'savePreset' : IDL.Func(
      [IDL.Text, MaterialType, GenerationParameters],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const GenerationParameters = IDL.Record({
    'roughness' : IDL.Float64,
    'patternStyle' : IDL.Text,
    'metalness' : IDL.Float64,
    'colorPalette' : IDL.Vec(IDL.Text),
    'tilingScale' : IDL.Float64,
  });
  const MaterialType = IDL.Variant({
    'metal' : IDL.Null,
    'organic' : IDL.Null,
    'wood' : IDL.Null,
    'stone' : IDL.Null,
    'plastic' : IDL.Null,
    'fabric' : IDL.Null,
  });
  const TexturePreset = IDL.Record({
    'owner' : IDL.Principal,
    'name' : IDL.Text,
    'parameters' : GenerationParameters,
    'timestamp' : IDL.Int,
    'materialType' : MaterialType,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deletePreset' : IDL.Func([IDL.Text], [], []),
    'getAllPresets' : IDL.Func([], [IDL.Vec(TexturePreset)], ['query']),
    'getAllPresetsByName' : IDL.Func([], [IDL.Vec(TexturePreset)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPreset' : IDL.Func([IDL.Text], [IDL.Opt(TexturePreset)], ['query']),
    'getPresetsByMaterialType' : IDL.Func(
        [MaterialType],
        [IDL.Vec(TexturePreset)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'savePreset' : IDL.Func(
        [IDL.Text, MaterialType, GenerationParameters],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };