/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface GenerationParameters {
  'roughness' : number,
  'patternStyle' : string,
  'metalness' : number,
  'colorPalette' : Array<string>,
  'tilingScale' : number,
}
export type MaterialType = { 'metal' : null } |
  { 'organic' : null } |
  { 'wood' : null } |
  { 'stone' : null } |
  { 'plastic' : null } |
  { 'fabric' : null };
export interface TexturePreset {
  'owner' : Principal,
  'name' : string,
  'parameters' : GenerationParameters,
  'timestamp' : bigint,
  'materialType' : MaterialType,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deletePreset' : ActorMethod<[string], undefined>,
  'getAllPresets' : ActorMethod<[], Array<TexturePreset>>,
  'getAllPresetsByName' : ActorMethod<[], Array<TexturePreset>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPreset' : ActorMethod<[string], [] | [TexturePreset]>,
  'getPresetsByMaterialType' : ActorMethod<
    [MaterialType],
    Array<TexturePreset>
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'savePreset' : ActorMethod<
    [string, MaterialType, GenerationParameters],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];